name: analytics-release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      git_user: ${{ secrets.MOBILE_GIT_USER_NAME }}
      git_token: ${{ secrets.GIT_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.ANDROID_SLACK_URL }}
      RELEASE_VARIANT: release

    steps:
      # Checkout the branch
      - name: Check out branch
        id: check_out_branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ANDROID_PAT }}
      # Set up slack notifier
      - uses: act10ns/slack@v1
        id: slack_notifier_setup
        with:
          status: starting
        if: always()
      # Decrypt release keystore and release properties file from github secrets. Workflow triggers qaDebuggableRelease which depends upon release config
      - name: Decrypt files
        id: decrypt_files
        run: |
          echo "${{ secrets.MOBILE_LOCAL_PROPERTIES }}" > local.properties.asc
          gpg -d --passphrase "${{ secrets.ANDROID_DECRYPT_KEY }}" --batch local.properties.asc > local.properties
      # Build aar
      - name: Build aar
        id: build_aar
        run: |
          ./gradlew dummy-sdk:build
      # Publish aar
      - name: Publish aar
        id: publish_aar
        run: |
          ./gradlew dummy-sdk:publishReleasePublicationToGitHubPackagesRepository
      # Create tag
      - name: Create tag
        id: create_tag
        run: |
          git config --global user.email "${{ secrets.MOBILE_GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.MOBILE_GIT_USER_NAME }}"
          ./gradlew dummy-sdk:createTag
          echo ::set-output name=tag_name::$(git describe --tags `git rev-list --tags --max-count=1`)
      # create release on github repo
      # GITHUB_TOKEN secret is a GitHub App installation access token which is automatically generated
      # it can be used to authenticate on behalf of the GitHub App installed on your repository
      # Refer - https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
          release_name: ${{ steps.create_tag.outputs.tag_name }}
          body_path: ./release-notes.txt
          draft: false
          prerelease: false
      # Send the workflow status on slack
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()